### ISSUE TITLE
Bugs in v3.0.4

### ISSUE THREAD

**Issue by skuske** [tokkonopapa/WordPress-IP-Geo-Block#19]
The latest version produces the following errors:

Warning: implode(): Invalid arguments passed in /plugins/ip-geo-block/admin/includes/tab-settings.php on line 295

and

IP Geo Block: /plugins/ip-geo-block/classes/class-ip-geo-block-logs.php (685) Unknown column 'asn' in 'field list'

**Comment by skuske** [comment]
Additionally, the option

"Remove all settings at uninstallation" 

does not save its setting - it always reverts back to the previous state.

**Comment by tokkonopapa** [comment]
Hi @skuske,

Sorry for the issue. I've fixed it and will release 3.0.4.1 soon. Please refer to https://wordpress.org/support/topic/error-on-updating-3-0-4/

Regarding to "Remove all settings at uninstallation", it might be caused by "Warning: implode(): Invalid arguments passed in /plugins/ip-geo-block/admin/includes/tab-settings.php on line 295". So please once deactivate and activate again.

Thanks you for the notices.

**Comment by skuske** [comment]
Cool, thanks. :)

Deactivating and re-activating the plugin does not fix the problem with saving the 'Remove all settings...' option. It stays enabled (ticked), and I cannot uncheck that box, although it says that settings were saved. I also do not get any error or something. It just does not work for me...

**Comment by tokkonopapa** [comment]
OK, I've got a reason and fixed in this commit: https://github.com/tokkonopapa/WordPress-IP-Geo-Block/commit/f471769f2007bffbb4d97b81fa9eb3962bdb31ff

Thank you for your cooperation!
